baseurl = "http://gopherconbr.org"
languageCode = "pt-BR"
title = "GopherCon Brasil 2023"
contentdir = "content/"
publishdir = "public/"

[params]
    locale = "pt-BR"

[taxonomies]
  sponsor = "sponsors"
  speaker = "speakers"
  event = "events"
  day = "days"
